project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - Classes/EAGER.qmd
    - Classes/UC_Berkeley.qmd
    - Classes/IntDataAnalysis.qmd
    - Classes/DataScience.qmd
    - Classes/CompStats.qmd
    - Projects/EAGER/Blog.qmd  
    - Projects/DataScience/SoCalRentProject.qmd
    - Projects/DataScience/FlowerProject.qmd
    - Projects/CompStats/ForniteMicroTransactions/Fornite_MicroTransactions.qmd
    - Projects/CompStats/Baseball/Baseball.qmd
    - Projects/CompStats/LongCOVID/LongCOVID.qmd
    - Projects/IntDataAnalysis/CarPrices/Cars4Sale.qmd
    - Projects/IntDataAnalysis/COVID/COVID.qmd
    - Projects/IntDataAnalysis/Earthquakes/Earthquake.qmd

website:
  title: "<b>Natalie Torres</b>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Classes/EAGER.qmd
        text: EAGER
      - text: Classes
        menu:
          - href: Classes/DataScience.qmd
            text: Data Science
          - href: Classes/CompStats.qmd
            text: Comp Stats
          - href: Classes/IntDataAnalysis.qmd
            text: Int Data Analysis
      - href: Classes/UC_Berkeley.qmd
        text: Research

format:
  html:
    theme: minty
    toc: true
    code-fold: true
    code-summary: "Show code"
    highlight-style: dracula
